### ISSUE TITLE
[feedback]: Changing environment variable on API response

### ISSUE THREAD

**Issue by dotriz** [RapidAPI/feedback#16] opened 2022-08-01 11:42 UTC
### What do you think of the extension?

Add an option, just like Postman, to change a variable value upon receiving an API response. In many cases, specific values are required in subsequent API calls, like User Token etc, so this feature is a must have.

**Comment by estruyf** [comment] 2022-08-01 13:00
@dotriz, to reframe this, do you want to use a value from one API call in another API call?

**Comment by dotriz** [comment] 2022-08-01 16:36
> @dotriz, to reframe this, do you want to use a value from one API call in another API call?

Yes, exactly

**Comment by dallenbaldwin** [comment] 2022-08-01 17:14
I'd like to second this request. I just downloaded the VS Code Extension after seeing a showcase from a coding YouTuber. I love the look and feel. I also feel the Environment Group feature is superb and will definitely be showing up everywhere else very soon. The one thing preventing me from moving from Thunder Client (VS Code ext) to this client is the ability to set environment variables from request responses

For example, when I run a saved request, say one that gets an access token from a token endpoint, I'd like to use a field in the response to overwrite an environment variable in a specific Environment Group (which would then propagate to any environments under that group). 

Here's what it looks like in Thunder Client. Thunder Client uses an active environment pattern. {{access_token}} is a variable in my active environment

![image](https://user-images.githubusercontent.com/14098845/182204957-f54ed073-6523-4dcc-a02f-67ff30eaab89.png)

**Comment by estruyf** [comment] 2022-08-02 10:35
@dotriz and @dallenbaldwin, this is possible with our dynamic value logic and the special `{response body path}` functionality.

With that functionality, you can reuse the outcome of an already performed request. 

Here is a demo:

https://user-images.githubusercontent.com/2900833/182354416-2511d5ae-157b-4456-9336-310de016fb49.mp4

**Comment by dotriz** [comment] 2022-08-02 11:39
@estruyf thanks for explaining this. This option can be handy. But still some times we want to hard code a token/parameter to test an API, and for that global variables can be really useful. If we can just overwrite those variable with API response, both use cases can be served.

**Comment by estruyf** [comment] 2022-08-02 12:08
The same can be achieved in an environment variable.

**Comment by aumi364** [comment] 2022-08-07 08:03
@estruyf But can't get the expected behavior in the environment section. I have attached the recording below.
[Attachment](https://user-images.githubusercontent.com/16230189/183281354-eed9d0f6-3f8c-48ac-9d7b-fc987000f577.webm)
.

**Comment by estruyf** [comment] 2022-08-12 07:53
This issue got fixed in the latest version.

**Closed by estruyf** 2022-08-12 07:53 UTC
Labels: question
